### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [notofonts/music#10]
.

**Comment by simoncozens** [comment]
Looks like these apps are failing to do mark attachment. I suspect the problem is that they aren't aware of the `musc` opentype script tag, but even then the lookups are also in the default languagesystem, so it shouldn't be a problem.

Can you confirm which build you were using? (full/googlefonts/hinted/unhinted) If the problem occurs with the full and googlefonts builds, it might be a problem with the font merger. If it occurs with hinted or unhinted, then it's unfortunately just an Adobe bug, not a Noto one.

**Comment by curya** [comment]
@simoncozens Sorry for the late reply! I didn't notice your post.

I'm using NotoMusic-Regular.ttf in the Full folder downloaded from this repo's release page.

It looks like version 2.003 has fixed this issue:
![image](https://github.com/notofonts/music/assets/43591297/ec557c5e-0112-494a-915b-14958b3364b6)

But I did find another issue while testing... There seems to be an overlapping problem with these characters:
♩𝅭♩𝅭
𝅘𝅥𝅭𝅘𝅥𝅭
![image](https://github.com/notofonts/music/assets/43591297/c2e0ad36-b95c-4aca-b3b9-336fc772f4d6)
