### ISSUE TITLE
Eighth note (♪, U+266A) size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [notofonts/music#6]
```
Shouldn't the eighth note (and beamed eighth notes, U+266B, for that matter) 
have the size of uppercase letters (cap or ascender height) instead of 
lowercase (x-height)?


What version of the product are you using? On what operating system?
Noto Sans 1.04
```

Original issue reported on code.google.com by `eemail...@gmail.com` on 17 Apr 2015 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Confirming that the ♪ and ♫ are too small in Noto Sans and Noto Serif 
(compared with, say, Arial and Times).
```

Original comment by `roozbeh@google.com` on 13 May 2015 at 4:09
- Changed state: **Accepted**

**Comment by aaaxx** [comment]
Could this be corrected, please? I know there are probably more pressing matters but this should really be a quick and easy fix.

**Comment by nizarsq** [comment]
Look like 266A 266B are consistent now. Closing this bug for now.
<img width="1126" alt="Screen Shot 2020-08-01 at 8 17 35 PM" src="https://user-images.githubusercontent.com/22158882/89114672-0d046080-d434-11ea-9f7f-68a776b0880d.png">

**Comment by dscorbett** [comment]
> Look like 266A 266B are consistent now.

That is not what this report is about. These characters are still shorter than caps height. For example, here is <U+1D213, U+2669> in version 2.002:
![𝈓♩](https://user-images.githubusercontent.com/1124347/189548082-c08eb576-c182-4a52-b032-784c4e2e8d6d.png)

Compare <U+0046, U+2669> in Noto Sans Symbols 2.001, where the note is taller, though still not quite caps height.
![F♩](https://user-images.githubusercontent.com/1124347/189548133-1b087b88-7a7c-4764-b7df-fa284f95a60c.png)

There is no standard for how tall these dingbats should be, so the current glyphs are not necessarily wrong, but this issue was closed based on a misunderstanding, so it should be reevaluated.

**Comment by simoncozens** [comment]
I'm going to close this because I don't believe that the dingbat glyphs are actually all that useful for musical typesetting, which is the bulk of what this font is about, and as you mention there is no standard for how tall these are meant to be anyway.
