### ISSUE TITLE
Any plans to make the font SMuFL-compatible?

### ISSUE THREAD

**Issue by mahalisyarifuddin** [notofonts/music#8]
I got to know this open standard named [SMuFL](https://w3c.github.io/smufl), used for musical notation exchanges. The standard itself featured thousands of characters, way more than the Musical Symbols block can offer, even though this would resort to the use of Private Use Area block, including the "real" Unicode codepoints is still recommended for this standard.

Noto Music only supports the Musical Symbols block.

So I would like to know if there's any plan to support the standard?

Thank you.

**Comment by simoncozens** [comment]
I'm afraid we're not going to do that - there are various reasons (obviously a big one is that it's a lot of work!) but the main one is that Noto has to stick to covering Unicode and avoid using PUA codepoints in public fonts; this is especially important because Noto fonts are used in a fallback stack, and we don't necessarily want music symbols to turn up in any document that has PUA codepoints in it.

**Comment by ghost** [comment]
@mahalisyarifuddin I don't know much about SMuFL but it seems there are many musical characters not yet in Unicode. Have you (or whoever maintains SMuFL) considered submitting a proposal to get them included in a new musical block?

Here's some helpful information:

**Submitting Character Proposals, Unicode Consortium** https://www.unicode.org/pending/proposals.html

**Submitting Successful Character and Script Proposals (FAQ), Unicode Consortium** https://www.unicode.org/faq/char_proposal.html

**The Unicode® Standard: A Technical Introduction, Unicode Consortium** https://www.unicode.org/standard/principles.html. The "principles of the Unicode Standard" are laid out in a section of this chapter.
